- name: Deploy Smart Ticket App
  hosts: localhost
  gather_facts: no

  tasks:

    - name: Stop old container
      shell: docker rm -f ticket-container || true

    - name: Build Docker Image
      shell: docker build -t ticket-app ..

    - name: Run Docker Container
      shell: docker run -d -p 3002:3000 --name ticket-container ticket-app

    - name: Show Running Containers
      shell: docker ps
      register: output

    - name: Print Output
      debug:
        var: output.stdout_lines